#!/usr/bin/env python3
"""Extract the Source Serif 4 600 lowercase 't' into the brand source module.

This is a development-time generator only. It reads the font already present in
public/fonts; it does not copy or redistribute the font.

Requirements (outside the repo):
    python -m pip install "fonttools[brotli]"
"""

from __future__ import annotations

import json
import math
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / "public/fonts/source-serif-4-latin-600-normal.woff2"
OUT = ROOT / "src/brand/mark.mjs"

# Review-approved placement for Source Serif 4 600 `t`.
TRANSFORM = "translate(6.863 28.21) scale(0.039826 -0.039826)"
VIEW = "0 0 32 32"
VIEW_TIGHT = "4.39 2.23 27.23 27.23"
DOT = {"x": 24.25, "y": 24.25, "w": 4.25, "h": 4.25, "r": 0.25}


def fmt(v: float) -> str:
    s = f"{v:.2f}"
    return s.rstrip("0").rstrip(".") if "." in s else s


def main() -> None:
    if not FONT.exists():
        raise SystemExit(f"Missing font: {FONT}")

    font = TTFont(FONT)
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    glyph_name = cmap.get(ord("t"))
    if not glyph_name:
        raise SystemExit("The 600 face does not contain lowercase 't'.")

    glyph = glyph_set[glyph_name]

    bounds_pen = BoundsPen(glyph_set)
    glyph.draw(bounds_pen)
    bounds = bounds_pen.bounds
    if not bounds:
        raise SystemExit("Could not determine glyph bounds for lowercase 't'.")

    x_min, y_min, x_max, y_max = bounds

    # Fail loudly if the project's font changes enough that the reviewed transform
    # is no longer trustworthy. Small subsetting/version differences are tolerated.
    expected = (16, -12, 361, 633)
    actual = (x_min, y_min, x_max, y_max)
    tolerance = 4
    if any(abs(a - e) > tolerance for a, e in zip(actual, expected)):
        raise SystemExit(
            "Source Serif 4 metrics differ from the reviewed face.\n"
            f"Expected approximately {expected}; got {tuple(round(v, 2) for v in actual)}.\n"
            "Recompute the transform instead of silently shipping a shifted mark."
        )

    units_per_em = font["head"].unitsPerEm
    if units_per_em != 1000:
        raise SystemExit(
            "Source Serif 4 units per em differ from the reviewed face.\n"
            f"Expected 1000; got {units_per_em}.\n"
            "Recompute the transform instead of silently shipping a shifted mark."
        )

    advance_width = glyph.width
    if advance_width != 368:
        raise SystemExit(
            "Source Serif 4 lowercase 't' advance width differs from the reviewed face.\n"
            f"Expected 368; got {advance_width}.\n"
            "Recompute the transform instead of silently shipping a shifted mark."
        )

    path_pen = SVGPathPen(glyph_set, ntos=fmt)
    glyph.draw(path_pen)
    path = path_pen.getCommands()

    OUT.parent.mkdir(parents=True, exist_ok=True)
    content = f'''// GENERATED by scripts/extract-brand-glyph.py. Do not hand-edit.\n\nexport const MARK_T = {json.dumps(path)};\nexport const MARK_T_TRANSFORM = {json.dumps(TRANSFORM)};\nexport const MARK_DOT = {json.dumps(DOT, separators=(",", ":"))};\nexport const MARK_VIEW = {json.dumps(VIEW)};\nexport const MARK_VIEW_TIGHT = {json.dumps(VIEW_TIGHT)};\nexport const MARK_FONT_BOUNDS = {json.dumps([round(v, 4) for v in actual])};\n'''
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} from {FONT.relative_to(ROOT)}")
    print(f"glyph={glyph_name} bounds={tuple(round(v, 2) for v in actual)}")


if __name__ == "__main__":
    main()
